version: "3"
services:
  example-app:
    build:
      context: "."
      args:
        BUILD_ENV: development
    command: sh -c "yarn install && yarn start"
    expose:
      - "3000"
    volumes:
      - .:/example-app/:rw
    environment:
      NODE_ENV: development

  gateway:
    build: ../gateway
    links:
      - example-app
    ports:
      - "80:80"
