version: "3"
services:
  example-app:
    build:
      context: "."
      args:
        BUILD_ENV: development
    command: sh -c "yarn install && yarn start"
    expose:
      - "3000"
    volumes:
      - .:/example-app/:rw
    environment:
      NODE_ENV: development
    links:
      - api

  api:
    build: ../api
    expose:
      - "4000"

  gateway:
    build: ../gateway
    links:
      - example-app
      - api
    ports:
      - "80:80"
