version: "3"
services:
  example-app:
    build:
      context: example-app
      args:
        BUILD_ENV: production
    expose:
      - "3000"

  gateway:
    build: gateway
    links:
      - example-app
    ports:
      - "80:80"